entryPoints:
    web:
        address: ":80"

    websecure:
        address: ":443"

providers:
    docker:
        exposedbydefault: false
        network: gateway
    file:
        filename: /etc/traefik/traefik.dev.local-certs.yml
        watch: true

api:
    dashboard: true
    insecure: true

log:
    level: DEBUG
#accessLog: {}
