entryPoints:
    web:
        address: ":80"

    websecure:
        address: ":443"

providers:
    docker:
        exposedbydefault: false
        network: gateway

certificatesResolvers:
    myresolver:
        acme:
            email: $EMAIL_ADDRESS
            storage: /letsencrypt/acme.json
            httpChallenge:
                entryPoint: http
            caserver: https://acme-staging-v02.api.letsencrypt.org/directory

#log:
#    level: DEBUG
#accessLog: {}
